apiVersion: v1
kind: Service
metadata:
  name: django-app
  namespace: csv-processor
spec:
  type: NodePort  
  selector:
    app: django-app
  ports:
    - port: 8000           
      targetPort: 8000     
      nodePort: 30080      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: csv-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: csv-app-image
          imagePullPolicy: Never
          command: ["/app/entrypoint.sh"]
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: file_processor.settings
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/postgres
            - name: REDIS_URL
              value: redis://redis:6379
            - name: CELERY_BROKER_URL
              value: amqp://guest:guest@rabbitmq:5672//
