apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: csv-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: csv-app-image
          imagePullPolicy: Never
          command: ["celery", "-A", "file_processor", "worker", "-E", "-l", "info"]
          env:
            - name: CELERY_BROKER_URL
              value: amqp://guest:guest@rabbitmq:5672//
            - name: REDIS_URL
              value: redis://redis:6379
